In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
import os

directory_path = 'C:/Users/Sakshi/Desktop/DATASETS/TEXT FORMAT'

# List files with the .txt extension
ieee_files = [doc for doc in os.listdir(directory_path) if doc.endswith('.txt')]

# Initialize a list to store the contents of each file
ieee_data = []

for file in ieee_files:
    file_path = os.path.join(directory_path, file)  # Construct the full file path
    try:
        with open(file_path, 'r', encoding='utf-8') as file_contents:
            content = file_contents.read()
            ieee_data.append(content)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except PermissionError:
        print(f"Permission denied for file: {file_path}")
    except Exception as e:
        print(f"An error occurred while reading {file_path}: {str(e)}")

# Now, ieee_data contains the contents of the valid files.


In [5]:
ieee_data

['Received April 5, 2020, accepted April 14, 2020, date of publication April 17, 2020, date of current version May 5, 2020.\nDigital Object Identifier 10.1109/ACCESS.2020.2988510\n\nArtificial Intelligence in Education: A Review\nLIJIA CHEN1 , PINGPING CHEN\n\n2,4 , (Member, IEEE), AND ZHIJIAN LIN\n\n1 School of Design, Yango University, Fuzhou 350015, China\n\n3 , (Member, IEEE)\n\n2 School of Advanced Manufacturing, Science Park of Fuzhou University, Jinjiang 362251, China\n3 School of Information, Fuzhou University, Fuzhou 35008, China\n\nCorresponding author: Pingping Chen (ppchen.xm@gmail.com)\nThis work was supported in part by the Humanities and Social Science Planning Funds of Fujian Province under Grant 275 JAS19453, and\nin part by the Distinguished Scholar Grant of Educational Commission of Fujian Province.\n\nABSTRACT The purpose of this study was to assess the impact of Artificial Intelligence (AI) on education.\nPremised on a narrative and framework for assessing AI ident

In [6]:
 def vectorize(text):
        return TfidfVectorizer().fit_transform(text).toarray()

In [7]:
def similarity(doc1,doc2):
    return cosine_similarity([doc1,doc2])

In [8]:
vectors=vectorize(ieee_data)

In [9]:
s_vectors=list(zip(ieee_files,vectors))

In [10]:
s_vectors

[('Artificial_Intelligence_in_Education_A_Review.txt',
  array([0., 0., 0., ..., 0., 0., 0.])),
 ('Digital_Twin_Enabling_Technologies_Challenges_and_Open_Research.txt',
  array([0.        , 0.00185887, 0.        , ..., 0.        , 0.        ,
         0.        ])),
 ('dummy.txt', array([0., 0., 0., ..., 0., 0., 0.])),
 ('dummy2.txt', array([0., 0., 0., ..., 0., 0., 0.])),
 ('Machine_Learning_Operations_MLOps_Overview_Definition_and_Architecture.txt',
  array([0.00173302, 0.        , 0.00267089, ..., 0.        , 0.        ,
         0.        ])),
 ('Peeking_Inside_the_Black-Box_A_Survey_on_Explainable_Artificial_Intelligence_XAI(1).txt',
  array([0.        , 0.        , 0.        , ..., 0.        , 0.00158864,
         0.00158864])),
 ('SegNet_A_Deep_Convolutional_Encoder-Decoder_Architecture_for_Image_Segmentation.txt',
  array([0.00253367, 0.00143379, 0.        , ..., 0.        , 0.        ,
         0.        ])),
 ('Temozolomide_in_Combination_With_NF-B_Inhibitor_Significantly_Dis

In [11]:
plagiarism_results = set()

In [12]:
def check_plagiarism():
    global s_vectors
    for ieee_a,text_vector_a in s_vectors:
        new_vectors = s_vectors.copy()
        current_index = new_vectors.index((ieee_a,text_vector_a))
        print(current_index)
        for ieee_b,text_vector_b in new_vectors:
            sim_score = similarity(text_vector_a,text_vector_b)[0][1]
            ieee_pair = sorted((ieee_a,ieee_b))
            score=(ieee_pair[0],ieee_pair[1],sim_score)
            plagiarism_results.add(score)
            print(score)
    return plagiarism_results

In [13]:
for data in check_plagiarism():
    print(data)

0
('Artificial_Intelligence_in_Education_A_Review.txt', 'Artificial_Intelligence_in_Education_A_Review.txt', 0.9999999999999958)
('Artificial_Intelligence_in_Education_A_Review.txt', 'Digital_Twin_Enabling_Technologies_Challenges_and_Open_Research.txt', 0.6790427042581798)
('Artificial_Intelligence_in_Education_A_Review.txt', 'dummy.txt', 0.5236709582209799)
('Artificial_Intelligence_in_Education_A_Review.txt', 'dummy2.txt', 0.41095120858902134)
('Artificial_Intelligence_in_Education_A_Review.txt', 'Machine_Learning_Operations_MLOps_Overview_Definition_and_Architecture.txt', 0.7221014115381089)
('Artificial_Intelligence_in_Education_A_Review.txt', 'Peeking_Inside_the_Black-Box_A_Survey_on_Explainable_Artificial_Intelligence_XAI(1).txt', 0.7400339206155359)
('Artificial_Intelligence_in_Education_A_Review.txt', 'SegNet_A_Deep_Convolutional_Encoder-Decoder_Architecture_for_Image_Segmentation.txt', 0.617925826737256)
('Artificial_Intelligence_in_Education_A_Review.txt', 'Temozolomide_in_Co

In [39]:
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import numpy as np

# Download NLTK resources (only need to do this once)
nltk.download('punkt')
nltk.download('stopwords')

def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.lower()
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    stemmer = PorterStemmer()
    filtered_tokens = [stemmer.stem(token) for token in tokens if token not in stop_words]
    return ' '.join(filtered_tokens)

def vectorize(text):
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(text)
    return tfidf_matrix.toarray(), tfidf_vectorizer

def similarity(doc1, doc2):
    return cosine_similarity(doc1.reshape(1, -1), doc2.reshape(1, -1))[0][0]

def check_plagiarism(new_file_path, existing_files, tfidf_vectorizer):
    with open(new_file_path, 'r', encoding='utf-8') as new_file_contents:
        new_file_content = new_file_contents.read()
        preprocessed_new_file_content = preprocess_text(new_file_content)
        new_vector = tfidf_vectorizer.transform([preprocessed_new_file_content]).toarray()
        plagiarism_results = set()
        for file_name, text_vector in existing_files:
            sim_score = similarity(new_vector, text_vector)
            file_pair = sorted((os.path.basename(new_file_path), file_name))
            score = (file_pair[0], file_pair[1], sim_score)
            plagiarism_results.add(score)
        return plagiarism_results

directory_path = 'C:/Users/Sakshi/Desktop/DATASETS/TEXT FORMAT'

# List files with the .txt extension
ieee_files = [doc for doc in os.listdir(directory_path) if doc.endswith('.txt')]

# Initialize a list to store the contents of each file
ieee_data = []

for file in ieee_files:
    file_path = os.path.join(directory_path, file)
    try:
        with open(file_path, 'r', encoding='utf-8') as file_contents:
            content = file_contents.read()
            ieee_data.append(content)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except PermissionError:
        print(f"Permission denied for file: {file_path}")
    except Exception as e:
        print(f"An error occurred while reading {file_path}: {str(e)}")

# Preprocess and vectorize existing data
preprocessed_ieee_data = [preprocess_text(text) for text in ieee_data]
vectors, tfidf_vectorizer = vectorize(preprocessed_ieee_data)
existing_files = list(zip(ieee_files, vectors))

# Example usage:
new_file_path = 'C:/Users/Sakshi/Desktop/DATASETS/TEXT FORMAT/same.txt'  # Replace with the actual path to the new file
plagiarism_results = check_plagiarism(new_file_path, existing_files, tfidf_vectorizer)

for data in plagiarism_results:
    print(data)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Sakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


('dummy.txt', 'same.txt', 0.07007385955551726)
('Machine_Learning_Operations_MLOps_Overview_Definition_and_Architecture.txt', 'same.txt', 0.11265942755836914)
('dummy2.txt', 'same.txt', 0.07830037497518283)
('Digital_Twin_Enabling_Technologies_Challenges_and_Open_Research.txt', 'same.txt', 0.6499563972769611)
('Peeking_Inside_the_Black-Box_A_Survey_on_Explainable_Artificial_Intelligence_XAI(1).txt', 'same.txt', 0.1016033589935467)
('Terahertz_Band_The_Last_Piece_of_RF_Spectrum_Puzzle_for_Communication_Systems.txt', 'same.txt', 0.10757730124482319)
('SegNet_A_Deep_Convolutional_Encoder-Decoder_Architecture_for_Image_Segmentation.txt', 'same.txt', 0.06329362316885735)
('Temozolomide_in_Combination_With_NF-B_Inhibitor_Significantly_Disrupts_the_Glioblastoma_Multiforme_Spheroid_Formation.txt', 'same.txt', 0.030626080407562824)
('hello.txt', 'same.txt', 0.0)
('Artificial_Intelligence_in_Education_A_Review.txt', 'same.txt', 0.145978538899406)
('same.txt', 'same.txt', 1.0000000000000002)


In [40]:
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import numpy as np
import pandas as pd  # Import Pandas for DataFrame

# Download NLTK resources (only need to do this once)
nltk.download('punkt')
nltk.download('stopwords')

def preprocess_text(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = text.lower()
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    stemmer = PorterStemmer()
    filtered_tokens = [stemmer.stem(token) for token in tokens if token not in stop_words]
    return ' '.join(filtered_tokens)

def vectorize(text):
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(text)
    return tfidf_matrix.toarray(), tfidf_vectorizer

def similarity(doc1, doc2):
    return cosine_similarity(doc1.reshape(1, -1), doc2.reshape(1, -1))[0][0]

def check_plagiarism(new_file_path, existing_files, tfidf_vectorizer):
    with open(new_file_path, 'r', encoding='utf-8') as new_file_contents:
        new_file_content = new_file_contents.read()
        preprocessed_new_file_content = preprocess_text(new_file_content)
        new_vector = tfidf_vectorizer.transform([preprocessed_new_file_content]).toarray()
        similarity_scores = []  # List to store similarity scores
        for file_name, text_vector in existing_files:
            sim_score = similarity(new_vector, text_vector)
            similarity_scores.append(sim_score)
            file_pair = sorted((os.path.basename(new_file_path), file_name))
            score = (file_pair[0], file_pair[1], sim_score)
            plagiarism_results.add(score)
        avg_similarity = np.mean(similarity_scores)  # Calculate average similarity
        return avg_similarity

directory_path = 'C:/Users/Sakshi/Desktop/DATASETS/TEXT FORMAT'

# List files with the .txt extension
ieee_files = [doc for doc in os.listdir(directory_path) if doc.endswith('.txt')]

# Initialize a list to store the contents of each file
ieee_data = []

for file in ieee_files:
    file_path = os.path.join(directory_path, file)
    try:
        with open(file_path, 'r', encoding='utf-8') as file_contents:
            content = file_contents.read()
            ieee_data.append(content)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except PermissionError:
        print(f"Permission denied for file: {file_path}")
    except Exception as e:
        print(f"An error occurred while reading {file_path}: {str(e)}")

# Preprocess and vectorize existing data
preprocessed_ieee_data = [preprocess_text(text) for text in ieee_data]
vectors, tfidf_vectorizer = vectorize(preprocessed_ieee_data)
existing_files = list(zip(ieee_files, vectors))

# Example usage:
new_file_path = 'C:/Users/Sakshi/Desktop/DATASETS/TEXT FORMAT/same.txt'  # Replace with the actual path to the new file
avg_similarity = check_plagiarism(new_file_path, existing_files, tfidf_vectorizer)

# Create a DataFrame to store results
results_df = pd.DataFrame(columns=['File1', 'File2', 'Average Similarity'])
results_df.loc[0] = [os.path.basename(new_file_path), 'Existing Files', avg_similarity]

# Print the results DataFrame
print(results_df)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Sakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Sakshi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


      File1           File2  Average Similarity
0  same.txt  Existing Files            0.214552


In [41]:
import pickle

# Save tfidf_vectorizer and existing_files to pickle files
with open('tfidf_vectorizer.pickle', 'wb') as vectorizer_file:
    pickle.dump(tfidf_vectorizer, vectorizer_file)

with open('existing_files.pickle', 'wb') as files_file:
    pickle.dump(existing_files, files_file)
